jwt:
  key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
spring:
  datasource:
    url: jdbc:h2:mem:cargo_monitoring;DB_CLOSE_DELAY=-1
    username: username
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: h2
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    url: jdbc:h2:mem:cargo_monitoring;DB_CLOSE_DELAY=-1
    user: username
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true